[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "pyTMD"
version = "2.2.8"
description = "Python-based tidal prediction software for estimating ocean, load, solid Earth and pole tides"
keywords = [
    "Ocean Tides",
    "Load Tides",
    "Pole Tides",
    "Solid Earth Tides",
    "Tidal Prediction",
]
authors = [
    {name = "Tyler Sutterley"},
    {email = "tsutterl@uw.edu"}
]
maintainers = [
    {name = "pyTMD contributors"}
]
license = {file = "LICENSE"}
readme = {file = "README.md", content-type = "text/markdown"}

requires-python = "~=3.6"
dependencies = [
    "lxml",
    "netCDF4",
    "numpy",
    "pyproj",
    "python-dateutil",
    "scipy>=1.10.1",
    "timescale>=0.0.8",
]

classifiers=[
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Oceanography",
]

[project.urls]
Homepage = "https://pytmd.readthedocs.io"
Documentation = "https://pytmd.readthedocs.io"
Repository = "https://github.com/pyTMD/pyTMD"
Issues = "https://github.com/pyTMD/pyTMD/issues"

[project.optional-dependencies]
doc = ["docutils", "graphviz", "myst-nb", "numpydoc", "sphinx", "sphinx-argparse>=0.4", "sphinxcontrib-bibtex", "sphinx-design", "sphinx_rtd_theme"]
all = ["cartopy", "ipyleaflet", "ipywidgets", "jplephem", "jupyterlab", "matplotlib", "notebook", "pandas", "xarray"]
aws = ["dask", "geopandas", "h5netcdf", "obstore", "pyarrow", "s3fs", "zarr>=3"]
dev = ["flake8", "gh", "oct2py", "pytest>=4.6", "pytest-cov", "pytest-xdist"]

[project.scripts]
"fetch_arcticdata.py" = "pyTMD.datasets.fetch_arcticdata:main" 
"fetch_aviso_fes.py" = "pyTMD.datasets.fetch_aviso_fes:main" 
"fetch_gsfc_got.py" = "pyTMD.datasets.fetch_gsfc_got:main" 
"fetch_test_data.py" = "pyTMD.datasets.fetch_test_data:main" 
"reduce_otis.py" = "pyTMD.datasets.reduce_otis:main" 
"verify_box_tpxo.py" = "pyTMD.datasets.verify_box_tpxo:main" 
"arcticdata_tides.py" = "pyTMD.datasets.fetch_arcticdata:main" 
"aviso_fes_tides.py" = "pyTMD.datasets.fetch_aviso_fes:main" 
"gsfc_got_tides.py" = "pyTMD.datasets.fetch_gsfc_got:main" 
"reduce_OTIS_files.py" = "pyTMD.datasets.reduce_otis:main" 

[tool.setuptools.packages.find]
exclude = ["providers*", "run*", "test*"]

[tool.pytest.ini_options]
minversion = "6.0"
norecursedirs = ".git"
addopts = "-n auto --verbose --capture=no"
python_files = [
    "test*.py"
]
testpaths = [
    "test"
]

[tool.coverage.run]
branch = true
source = [
    "pyTMD",
    "test",
]
omit = [
    "setup.py",
    "conf.py",
    "pyTMD/datasets/*",
    "pyTMD/compute_tide_corrections.py",
    "test/_coefficients_to_json.py",
    "test/_def_to_json.py",
    "providers/*.py",
]

[tool.coverage.report]
show_missing = true
precision = 2

[tool.ruff]
line-length = 80
indent-width = 4

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = false

[tool.pixi.workspace]
name = "pytmd"
authors = ["pyTMD contributors"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tool.pixi.pypi-dependencies]
pyTMD = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
all = { features = ["all"], solve-group = "default" }
aws = { features = ["all", "aws"], solve-group = "default" }
dev = { features = ["all", "dev", "doc"], solve-group = "default" }
doc = { features = ["all", "doc"], solve-group = "default" }

[tool.pixi.tasks.start]
cmd = "jupyter lab"
cwd = "doc/source/notebooks"
description = "Start JupyterLab in the notebooks directory"

[tool.pixi.tasks.export-env]
args = [ { "arg" = "flags", "default" = "" } ]
cmd = "pixi workspace export conda-environment {{ flags }} > environment.yml"
description = "Export workspace to a conda environment file" 

[tool.pixi.feature.doc.tasks.docs]
args = [ { "arg" = "flags", "default" = "" } ]
cmd = "make html {{ flags }}"
cwd = "doc"
description = "Create HTML documentation with sphinx"

[tool.pixi.feature.dev.tasks.fetch]
cmd = "python -c 'import pyTMD; pyTMD.datasets.fetch_test_data()'"
description = "Fetch data needed to run the pytest suite"

[tool.pixi.feature.dev.tasks.test]
args = [ { "arg" = "flags", "default" = "" }, { "arg" = "test", "default" = "." } ]
cmd = "pytest {{ flags }} {{ test }}"
cwd = "test"
description = "Run the pytest suite"

[tool.pixi.feature.dev.tasks.lint]
args = [ { "arg" = "flags", "default" = "--select=E9,F63,F7,F82 --show-source" }, { "arg" = "test", "default" = "." } ]
cmd = "flake8 {{ test }} --count {{ flags }} --statistics --extend-exclude 'build/,run/,*.ipynb_checkpoints/,.pixi/'"
description = "Run flake8 to check for compilation errors"

[tool.pixi.dependencies]
numpy = "*"
netcdf4 = "*"
lxml = "*"
pyproj = "*"
python-dateutil = "*"
scipy = ">=1.16.0"
timescale = ">=0.0.8"

[tool.pixi.feature.all.dependencies]
cartopy = "*"
matplotlib = "*"
ipyleaflet = "*"
ipywidgets = "*"
jplephem = "*"
jupyterlab = "*"
pandas = "*"
notebook = "*"
xarray = "*"

[tool.pixi.feature.aws.dependencies]
dask = "*"
geopandas = "*"
h5netcdf = "*"
obstore = "*"
pyarrow = "*"
s3fs = "*"
zarr = ">=3"

[tool.pixi.feature.dev.dependencies]
flake8 = "*"
gh = "*"
oct2py = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"

[tool.pixi.feature.doc.dependencies]
docutils = "*"
graphviz = "*"
myst-nb = "*"
numpydoc = "*"
sphinx = "*"
sphinx-argparse = "*"
sphinxcontrib-bibtex = "*"
sphinx-design = "*"
sphinx_rtd_theme = "*"
