# This workflow will install Python dependencies and update the time and EOP files

name: Auto-Update Files

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev libproj-dev proj-data proj-bin \
            libgeos-dev libhdf5-dev libnetcdf-dev octave
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        pip install --upgrade pip
        pip install numpy
        pip install .
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Test with pytest
      run: |
        pytest test/test_leap_seconds.py test/test_time.py test/test_eop.py \
            --username=${{ secrets.EARTHDATA_USERNAME }} \
            --password=${{ secrets.EARTHDATA_PASSWORD }}
    - name: Check for changes
      id: changes
      run: |
        if [ -n "$(git status --porcelain)" ] ; then
            echo "::set-output name=detected::true";
            echo "::debug::Changes detected";
        else
            echo "::set-output name=detected::false";
            echo "::debug::No changes detected";
        fi
    - name: Create pull request
      if: steps.changes.outputs.detected == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        assignees: ${{ github.actor }}
        title: "Automatic time updates"
